// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartEnrol.Repositories.Models;

public partial class AccountSearchModel
{
    public int? AccountId { get; set; }

    public string? AccountName { get; set; }

    public string? Email { get; set; }

    public string? Password { get; set; }

    public int? RoleId { get; set; }

    public int? AreaId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public bool? IsActive { get; set; }
}