// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartEnrol.Repositories.Models;

public partial class Account
{
    public int AccountId { get; set; }

    public string AccountName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int RoleId { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<CharacteristicOfStudent> CharacteristicOfStudents { get; set; } = new List<CharacteristicOfStudent>();

    public virtual ICollection<Recommendation> Recommendations { get; set; } = new List<Recommendation>();

    public virtual Role Role { get; set; }

    public virtual ICollection<WishListItem> WishListItems { get; set; } = new List<WishListItem>();
}