// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartEnrol.Repositories.Models;

public partial class AdmissionMethodOfMajor
{
    public int AdmissionMethodsOfMajorId { get; set; }

    public int MajorId { get; set; }

    public int AdmissionMethodId { get; set; }

    public int AdmissionTargets { get; set; }

    public virtual AdmissionMethodOfUni AdmissionMethod { get; set; }

    public virtual Major Major { get; set; }
}