// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartEnrol.Repositories.Models;

public partial class AdmissionMethodOfUni
{
    public int AdmissionMethodId { get; set; }

    public string MethodName { get; set; }

    public int Year { get; set; }

    public int UniId { get; set; }

    public virtual ICollection<AdmissionMethodOfMajor> AdmissionMethodOfMajors { get; set; } = new List<AdmissionMethodOfMajor>();

    public virtual University Uni { get; set; }
}