// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace SmartEnrol.Repositories.Models;

public partial class AdmissionMethodOfMajor
{
    public int AdmissionMethodsOfMajorId { get; set; }

    public int UniMajorId { get; set; }

    public int AdmissionMethodOfUniId { get; set; }

    public int? AdmissionTargets { get; set; }

    public int? MajorScore { get; set; }

    public virtual AdmissionMethodOfUni AdmissionMethodOfUni { get; set; }

    public virtual UniMajor UniMajor { get; set; }
}