// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartEnrol.Repositories.Models;

public partial class CharacteristicOfField
{
    public int CharacteristicsOfFieldId { get; set; }

    public int FieldId { get; set; }

    public int CharacteristicId { get; set; }

    public int MinScore { get; set; }

    public virtual Characteristic Characteristic { get; set; }

    public virtual Field Field { get; set; }
}