// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartEnrol.Repositories.Models;

public partial class FieldOfUni
{
    public int FieldsOfUniId { get; set; }

    public int UniversityId { get; set; }

    public int FieldId { get; set; }

    public virtual Field Field { get; set; }

    public virtual ICollection<Major> Majors { get; set; } = new List<Major>();

    public virtual University University { get; set; }
}