// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartEnrol.Repositories.Models;

public partial class Field
{
    public int FieldId { get; set; }

    public string FieldName { get; set; }

    public virtual ICollection<CharacteristicOfField> CharacteristicOfFields { get; set; } = new List<CharacteristicOfField>();

    public virtual ICollection<FieldOfUni> FieldOfUnis { get; set; } = new List<FieldOfUni>();
}