// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartEnrol.Repositories.Models;

public partial class Major
{
    public int MajorId { get; set; }

    public string Name { get; set; }

    public int FieldOfUniId { get; set; }

    public virtual ICollection<AdmissionMethodOfMajor> AdmissionMethodOfMajors { get; set; } = new List<AdmissionMethodOfMajor>();

    public virtual FieldOfUni FieldOfUni { get; set; }

    public virtual ICollection<Recommendation> Recommendations { get; set; } = new List<Recommendation>();

    public virtual ICollection<WishListItem> WishListItems { get; set; } = new List<WishListItem>();
}