// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SmartEnrol.Repositories.Models;
using System;
using System.Collections.Generic;

namespace SmartEnrol.Repositories.Models;

public partial class UniMajor
{
    public int UniMajorId { get; set; }

    public int UniId { get; set; }

    public int? MajorId { get; set; }

    public virtual ICollection<AdmissionMethodOfMajor> AdmissionMethodOfMajors { get; set; } = new List<AdmissionMethodOfMajor>();

    public virtual Major Major { get; set; }

    public virtual ICollection<RecommendationDetail> RecommendationDetails { get; set; } = new List<RecommendationDetail>();

    public virtual University Uni { get; set; }

    public virtual ICollection<WishListItem> WishListItems { get; set; } = new List<WishListItem>();
}