// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartEnrol.Repositories.Models;

public partial class WishListItem
{
    public int Id { get; set; }

    public int AccountId { get; set; }

    public int MajorId { get; set; }

    public virtual Account Account { get; set; }

    public virtual Major Major { get; set; }
}