// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class CharacteristicOfMajor
{
    public int CharacteristicOfMajorId { get; set; }

    public int CharacteristicId { get; set; }

    public int MajorId { get; set; }

    public virtual Characteristic Characteristic { get; set; }

    public virtual Major Major { get; set; }
}