// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Major
{
    public int MajorId { get; set; }

    public string MajorName { get; set; }

    public virtual ICollection<CharacteristicOfMajor> CharacteristicOfMajors { get; set; } = new List<CharacteristicOfMajor>();

    public virtual ICollection<UniMajor> UniMajors { get; set; } = new List<UniMajor>();
}