// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class WishListItem
{
    public int ItemId { get; set; }

    public int? UniMajorId { get; set; }

    public int? UniId { get; set; }

    public int WishListId { get; set; }

    public bool IsActive { get; set; }

    public virtual University Uni { get; set; }

    public virtual UniMajor UniMajor { get; set; }

    public virtual WishList WishList { get; set; }
}